### PR TITLE
Fix Page Input No Result Display and Query Missing on Refresh

### LINKED ISSUE #133: No results label is not centered for inputs table
## 🙂 Expected behavior

The no results label for inputs table should be centered.

## 🫠 Actual behavior

The no results label for inputs table is not centered. Here's a screenshot:
no-results-label

## 🧪 Minimal test case

1. Go to `/inputs` page
2. Insert a search query that results in no entries being found
3. Observe the empty table and the no results label in it

## 🌎 Environment

Any network and any rollups version.

### PR DESCRIPTION
**Pull request by dandheedge**
Close #133 #134 #136

### CODE REVIEW

File: apps/web/src/components/search.tsx [hunk 1]
```diff
@@ -9,7 +9,7 @@ export type SearchProps = {
 
 const Search: React.FC<SearchProps> = ({ onChange, isLoading }) => {
     const { query, updateQueryParams } = useQueryParams();
-    const [keyword, setKeyword] = useState<string>("");
+    const [keyword, setKeyword] = useState<string>(query);
```
Comment (nevendyulgerov) [inline apps/web/src/components/search.tsx:12]: This persists the query and fetches the correct data based on the query, however sometimes it can be noticed that actually two requests are being made for the UI to show the filtered data:

https://github.com/cartesi/rollups-explorer/assets/6005179/2f66bd51-3aa0-4181-be20-34f51e502888

The first is with an empty query and the second with the one from the url. We can mitigate this by slightly extending the `Inputs` component:

```
const Inputs: FC<InputsProps> = ({
    orderBy = InputOrderByInput.TimestampDesc,
    applicationId,
}) => {
    const { query: urlQuery } = useQueryParams();
    const [query, setQuery] = useState(urlQuery);
    ...
```
This way, the initial request for inputs will always have the url query. The resulting UX is this:

https://github.com/cartesi/rollups-explorer/assets/6005179/2fb5bf5b-d6f4-42e6-bc99-7a15d90d5bcd

This way, the second request will hit the graphql cache (because the first and second query will be the same) and data will be pulled from it instead. The win is slightly better UI and one less request for the end user.

Comment (nevendyulgerov) [reply apps/web/src/components/search.tsx:12]: Let's also please add unit tests for this functionality to be on the safe side.

**Review by nevendyulgerov — COMMENTED** [review]
Nice work, @dandheedge ! We can do a couple of minor tweaks here and there to make some small improvements to the UI.

**Review by nevendyulgerov — APPROVED** [review]
Good stuff, @dandheedge, thanks for making those tweaks!

**Review by brunomenezes — APPROVED** [review]
LGTM. I did a quick rebase before merging.
